In [46]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
from pathlib import Path

In [47]:
file_path = Path('../data/raw/att_0_1778303821_c3a907.csv')
df = pd.read_csv(file_path,low_memory=False)

In [48]:
df.head()

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,1,DA Warner,TS Mills,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
1,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,2,DA Warner,TS Mills,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
2,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,3,DA Warner,TS Mills,S Dhawan,4,0,4,0,0,0,0,NaN,NaN
3,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,4,DA Warner,TS Mills,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
4,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,5,DA Warner,TS Mills,S Dhawan,0,2,2,2,0,0,0,NaN,NaN

In [49]:
df.columns.to_list()

['match_id',
 'date',
 'season',
 'event',
 'venue',
 'city',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'win_by_runs',
 'win_by_wickets',
 'player_of_match',
 'innings',
 'batting_team',
 'over',
 'ball',
 'batter',
 'bowler',
 'non_striker',
 'runs_batter',
 'runs_extras',
 'runs_total',
 'extras_wides',
 'extras_noballs',
 'extras_byes',
 'extras_legbyes',
 'wicket_kind',
 'wicket_player_out']

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289673 entries, 0 to 289672
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           289673 non-null  int64
 1   date               289673 non-null  object
 2   season             289673 non-null  object
 3   event              289673 non-null  object
 4   venue              289673 non-null  object
 5   city               277276 non-null  object
 6   team1              289673 non-null  object
 7   team2              289673 non-null  object
 8   toss_winner        289673 non-null  object
 9   toss_decision      289673 non-null  object
 10  winner             289673 non-null  object
 11  win_by_runs        133547 non-null  float64
 12  win_by_wickets     151146 non-null  float64
 13  player_of_match    288845 non-null  object
 14  innings            289673 non-null  int64
 15  batting_team       289673 non-null  object
 16  over               289673 non-null  int64
 17  ball               289673 non-null  int64
 18  batter             289673 non-null  object
 19  bowler             289673 non-null  object
 20  non_striker        289673 non-null  object
 21  runs_batter        289673 non-null  int64
 22  runs_extras        289673 non-null  int64
 23  runs_total         289673 non-null  int64
 24  extras_wides       289673 non-null  int64
 25  extras_noballs     289673 non-null  int64
 26  extras_byes        289673 non-null  int64
 27  extras_legbyes     289673 non-null  int64
 28  wicket_kind        14406 non-null   object
 29  wicket_player_out  14406 non-null   object
dtypes: float64(2), int64(11), object(17)
memory usage: 66.3+ MB

In [51]:
df.describe()

,match_id,win_by_runs,win_by_wickets,innings,over,ball,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes
count,2.896730e+05,133547.000000,151146.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000
mean,9.654832e+05,30.217766,6.115266,1.482793,9.190563,3.628167,1.285477,0.068184,1.353661,0.039565,0.004277,0.004705,0.019601
std,3.911715e+05,26.530801,1.823510,0.502495,5.680221,1.818353,1.659483,0.342671,1.645469,0.255822,0.068964,0.114363,0.190069
min,3.359820e+05,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483650e+05,11.000000,5.000000,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.082626e+06,22.000000,6.000000,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.304085e+06,41.000000,7.000000,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.529292e+06,146.000000,10.000000,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,5.000000,5.000000,4.000000,5.000000

In [52]:
df.isnull().sum()

match_id                  0
date                      0
season                    0
event                     0
venue                     0
city                  12397
team1                     0
team2                     0
toss_winner               0
toss_decision             0
winner                    0
win_by_runs          156126
win_by_wickets       138527
player_of_match         828
innings                   0
batting_team              0
over                      0
ball                      0
batter                    0
bowler                    0
non_striker               0
runs_batter               0
runs_extras               0
runs_total                0
extras_wides              0
extras_noballs            0
extras_byes               0
extras_legbyes            0
wicket_kind          275267
wicket_player_out    275267
dtype: int64

In [53]:
missing_city_venues = df[df['city'].isnull()]['venue'].unique()
print(missing_city_venues)

['Dubai International Cricket Stadium' 'Sharjah Cricket Stadium']

In [54]:
city_map = {
    'Dubai International Cricket Stadium': 'Dubai',
    'Sharjah Cricket Stadium': 'Sharjah'
}
df['city'] = df['city'].fillna(df['venue'].map(city_map))

In [55]:
# Combine team1 and team2 columns, get unique values, and drop any nulls
unique_teams = pd.concat([df['team1'], df['team2']]).dropna().unique()

# Sort them alphabetically so you can easily spot variations 
# (e.g., 'Rising Pune Supergiant' vs 'Rising Pune Supergiants')
unique_teams.sort()

# Print the list clearly
print(f"Total Unique Team Entries Found: {len(unique_teams)}\n")
print("--- Team List ---")
for team in unique_teams:
    print(team)

Total Unique Team Entries Found: 19

--- Team List ---
Chennai Super Kings
Deccan Chargers
Delhi Capitals
Delhi Daredevils
Gujarat Lions
Gujarat Titans
Kings XI Punjab
Kochi Tuskers Kerala
Kolkata Knight Riders
Lucknow Super Giants
Mumbai Indians
Pune Warriors
Punjab Kings
Rajasthan Royals
Rising Pune Supergiant
Rising Pune Supergiants
Royal Challengers Bangalore
Royal Challengers Bengaluru
Sunrisers Hyderabad

In [56]:
team_rebrands = {
    # 1. The Direct Name Changes
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    
    # 2. The Typo Fix
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
}

# Apply this to all team-related columns
columns_using_team_names = ['team1', 'team2', 'toss_winner', 'winner', 'batting_team']

for col in columns_using_team_names:
    df[col] = df[col].replace(team_rebrands)

In [57]:
# Get unique cities, drop nulls, and sort alphabetically
unique_cities = df['city'].dropna().unique()
unique_cities.sort()

print(f"Total Unique Cities Found: {len(unique_cities)}\n")
print("--- City List ---")
for city in unique_cities:
    print(city)

Total Unique Cities Found: 37

--- City List ---
Abu Dhabi
Ahmedabad
Bangalore
Bengaluru
Bloemfontein
Cape Town
Centurion
Chandigarh
Chennai
Cuttack
Delhi
Dharamsala
Dubai
Durban
East London
Guwahati
Hyderabad
Indore
Jaipur
Johannesburg
Kanpur
Kimberley
Kochi
Kolkata
Lucknow
Mohali
Mumbai
Nagpur
Navi Mumbai
New Chandigarh
Port Elizabeth
Pune
Raipur
Rajkot
Ranchi
Sharjah
Visakhapatnam

In [58]:
# The mapping dictionary based on your specific city list
city_rebrands = {
    'Bangalore': 'Bengaluru',
    'Mohali': 'Chandigarh',
    'New Chandigarh': 'Chandigarh'
}

# Apply the replacements
df['city'] = df['city'].replace(city_rebrands)

# Verify the changes
print(f"Cities reduced from 37 to {len(df['city'].dropna().unique())}")

Cities reduced from 37 to 34

In [59]:
# Get unique venues, drop nulls, and sort alphabetically
unique_venues = df['venue'].dropna().unique()
unique_venues.sort()

print(f"Total Unique Venues Found: {len(unique_venues)}\n")
print("--- Venue List ---")
for venue in unique_venues:
    print(venue)

Total Unique Venues Found: 59

--- Venue List ---
Arun Jaitley Stadium
Arun Jaitley Stadium, Delhi
Barabati Stadium
Barsapara Cricket Stadium, Guwahati
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
Brabourne Stadium
Brabourne Stadium, Mumbai
Buffalo Park
De Beers Diamond Oval
Dr DY Patil Sports Academy
Dr DY Patil Sports Academy, Mumbai
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam
Dubai International Cricket Stadium
Eden Gardens
Eden Gardens, Kolkata
Feroz Shah Kotla
Green Park
Himachal Pradesh Cricket Association Stadium
Himachal Pradesh Cricket Association Stadium, Dharamsala
Holkar Cricket Stadium
JSCA International Stadium Complex
Kingsmead
M Chinnaswamy Stadium
M Chinnaswamy Stadium, Bengaluru
M.Chinnaswamy Stadium
MA Chidambaram Stadium
MA Chidambaram Stadium, Chepauk
MA Chidambaram Stadium, Chepauk, Chennai
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh
Maharashtra Cricket Association Stadium
Maharashtra Cricket Association Stadium, Pune
Narendra Modi Stadium, Ahmedabad
Nehru Stadium
New Wanderers Stadium
Newlands
OUTsurance Oval
Punjab Cricket Association IS Bindra Stadium
Punjab Cricket Association IS Bindra Stadium, Mohali
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh
Punjab Cricket Association Stadium, Mohali
Rajiv Gandhi International Stadium
Rajiv Gandhi International Stadium, Uppal
Rajiv Gandhi International Stadium, Uppal, Hyderabad
Sardar Patel Stadium, Motera
Saurashtra Cricket Association Stadium
Sawai Mansingh Stadium
Sawai Mansingh Stadium, Jaipur
Shaheed Veer Narayan Singh International Stadium
Sharjah Cricket Stadium
Sheikh Zayed Stadium
St George's Park
Subrata Roy Sahara Stadium
SuperSport Park
Vidarbha Cricket Association Stadium, Jamtha
Wankhede Stadium
Wankhede Stadium, Mumbai
Zayed Cricket Stadium, Abu Dhabi

In [60]:
# The Master Venue Standardization Dictionary
venue_rebrands = {
    # Bengaluru
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    
    # Delhi (Historical renaming + city tag)
    'Feroz Shah Kotla': 'Arun Jaitley Stadium',
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    
    # Mumbai (Removing redundant city tags)
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',
    
    # Chennai
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
    
    # Ahmedabad (Historical renaming + city tag)
    'Sardar Patel Stadium, Motera': 'Narendra Modi Stadium',
    'Narendra Modi Stadium, Ahmedabad': 'Narendra Modi Stadium',
    
    # Pune (Corporate renaming + city tag)
    'Subrata Roy Sahara Stadium': 'Maharashtra Cricket Association Stadium',
    'Maharashtra Cricket Association Stadium, Pune': 'Maharashtra Cricket Association Stadium',
    
    # Punjab - Historic Stadium
    'Punjab Cricket Association Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association IS Bindra Stadium',
    
    # Punjab - New Stadium
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur': 'Maharaja Yadavindra Singh International Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh': 'Maharaja Yadavindra Singh International Cricket Stadium',
    
    # Hyderabad
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    
    # Kolkata
    'Eden Gardens, Kolkata': 'Eden Gardens',
    
    # Jaipur
    'Sawai Mansingh Stadium, Jaipur': 'Sawai Mansingh Stadium',
    
    # Dharamsala
    'Himachal Pradesh Cricket Association Stadium, Dharamsala': 'Himachal Pradesh Cricket Association Stadium',
    
    # Visakhapatnam
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    
    # Abu Dhabi
    'Zayed Cricket Stadium, Abu Dhabi': 'Sheikh Zayed Stadium'
}

# Apply the replacements
df['venue'] = df['venue'].replace(venue_rebrands)

# Verify the massive reduction in duplicates
print(f"Venues reduced from 59 to {len(df['venue'].dropna().unique())}")

Venues reduced from 59 to 36

In [61]:
print(df['season'].unique())

['2017' '2018' '2019' '2020/21' '2021' '2022' '2023' '2024' '2025'
 '2007/08' '2009' '2009/10' '2011' '2012' '2013' '2014' '2015' '2016'
 '2026']

In [62]:
# 1. Convert the text strings into native datetime objects
# (Pandas is usually smart enough to infer the YYYY-MM-DD format automatically)
df['date'] = pd.to_datetime(df['date'])

# 2. Extract the clean, 4-digit year from the date and overwrite the messy season column
df['season'] = df['date'].dt.year

# 3. Verify the changes
print("--- Cleaned Seasons ---")
print(df['season'].unique())
print(f"\nDate column type: {df['date'].dtype}")

--- Cleaned Seasons ---
[2017 2018 2019 2020 2021 2022 2023 2024 2025 2008 2009 2010 2011 2012
 2013 2014 2015 2016 2026]

Date column type: datetime64[ns]

In [63]:
df.head(1)

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,1082591,2017-04-05,2017,Indian Premier League,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh,1,Sunrisers Hyderabad,0,1,DA Warner,TS Mills,S Dhawan,0,0,0,0,0,0,0,NaN,NaN

In [64]:
# Sort from 2008 to present, and from Ball 1 to the final wicket
df = df.sort_values(by=[
    'date',      # 1st: The calendar day
    'match_id',  # 2nd: To separate afternoon vs evening games on the same day
    'innings',   # 3rd: 1st innings before 2nd innings
    'over',      # 4th: Over 0 to Over 19
    'ball'       # 5th: Ball 1 to Ball 6 (or 7/8 for extras)
])

# Reset the index so row 0 is truly the very first ball in IPL history
df = df.reset_index(drop=True)

# Verify the first ball ever bowled
df.head(1)

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,335982,2008-04-18,2008,Indian Premier League,M Chinnaswamy Stadium,Bengaluru,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,140.0,NaN,BB McCullum,1,Kolkata Knight Riders,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0,0,0,1,NaN,NaN

In [65]:
print(df['innings'].unique())

[1 2 3 4 5 6]

In [66]:
# Fill empty wicket fields with logical text
df['wicket_kind'] = df['wicket_kind'].fillna('No Wicket')
df['wicket_player_out'] = df['wicket_player_out'].fillna('Nobody')

In [67]:
# Step 1: Fill nulls with 0
df['win_by_runs'] = df['win_by_runs'].fillna(0)
df['win_by_wickets'] = df['win_by_wickets'].fillna(0)

# Step 2: Cast to integers (since you can't win by 2.5 runs)
df['win_by_runs'] = df['win_by_runs'].astype(int)
df['win_by_wickets'] = df['win_by_wickets'].astype(int)

In [68]:
# Tag unawarded matches clearly
df['player_of_match'] = df['player_of_match'].fillna('No Result')

In [69]:
# This should print a long list of zeros!
print(df.isna().sum())

match_id             0
date                 0
season               0
event                0
venue                0
city                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               0
win_by_runs          0
win_by_wickets       0
player_of_match      0
innings              0
batting_team         0
over                 0
ball                 0
batter               0
bowler               0
non_striker          0
runs_batter          0
runs_extras          0
runs_total           0
extras_wides         0
extras_noballs       0
extras_byes          0
extras_legbyes       0
wicket_kind          0
wicket_player_out    0
dtype: int64

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289673 entries, 0 to 289672
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           289673 non-null  int64
 1   date               289673 non-null  datetime64[ns]
 2   season             289673 non-null  int32
 3   event              289673 non-null  object
 4   venue              289673 non-null  object
 5   city               289673 non-null  object
 6   team1              289673 non-null  object
 7   team2              289673 non-null  object
 8   toss_winner        289673 non-null  object
 9   toss_decision      289673 non-null  object
 10  winner             289673 non-null  object
 11  win_by_runs        289673 non-null  int64
 12  win_by_wickets     289673 non-null  int64
 13  player_of_match    289673 non-null  object
 14  innings            289673 non-null  int64
 15  batting_team       289673 non-null  object
 16  over               289673 non-null  int64
 17  ball               289673 non-null  int64
 18  batter             289673 non-null  object
 19  bowler             289673 non-null  object
 20  non_striker        289673 non-null  object
 21  runs_batter        289673 non-null  int64
 22  runs_extras        289673 non-null  int64
 23  runs_total         289673 non-null  int64
 24  extras_wides       289673 non-null  int64
 25  extras_noballs     289673 non-null  int64
 26  extras_byes        289673 non-null  int64
 27  extras_legbyes     289673 non-null  int64
 28  wicket_kind        289673 non-null  object
 29  wicket_player_out  289673 non-null  object
dtypes: datetime64[ns](1), int32(1), int64(13), object(15)
memory usage: 65.2+ MB

In [71]:
# Combine all unique names from batters and bowlers into one master list
all_players = pd.concat([df['batter'], df['bowler']]).unique()

# Sort them alphabetically
all_players_sorted = np.sort(all_players)

# Print the first 50 to see what we are dealing with
print(all_players_sorted[:50])

['A Ashish Reddy' 'A Badoni' 'A Chandila' 'A Chopra' 'A Choudhary'
 'A Dananjaya' 'A Flintoff' 'A Kamboj' 'A Kumble' 'A Manohar' 'A Mhatre'
 'A Mishra' 'A Mithun' 'A Mukund' 'A Nehra' 'A Nel' 'A Nortje'
 'A Raghuvanshi' 'A Singh' 'A Symonds' 'A Tomar' 'A Uniyal' 'A Zampa'
 'AA Bilakhia' 'AA Chavan' 'AA Jhunjhunwala' 'AA Kazi' 'AA Kulkarni'
 'AA Noffke' 'AB Agarkar' 'AB Barath' 'AB Dinda' 'AB McDonald'
 'AB de Villiers' 'AC Blizzard' 'AC Gilchrist' 'AC Thomas' 'AC Voges'
 'AD Hales' 'AD Mascarenhas' 'AD Mathews' 'AD Nath' 'AD Russell'
 'AF Milne' 'AG Murtaza' 'AG Paunikar' 'AJ Finch' 'AJ Hosein' 'AJ Turner'
 'AJ Tye']

In [ ]:
from thefuzz import process

# 1. Gather every unique player name from all relevant columns
player_cols = ['batter', 'bowler', 'non_striker', 'player_of_match', 'wicket_player_out']
all_names = pd.concat([df[col] for col in player_cols]).dropna().unique()

# 2. Create a list to store our potential typos
potential_typos = []
processed_names = set() # To avoid checking the same name twice

print("Scanning for similar names...")

for name in all_names:
    if name not in processed_names:
        # Extract the top 3 matches for 'name' from the master list
        similar_names = process.extract(name, all_names, limit=4)
        
        # Keep matches that score between 85 and 99 
        # (100 is an exact match, below 85 is usually a different person)
        high_matches = [match for match in similar_names if 87 <= match[1] < 100]
        
        if high_matches:
            print(f"\nTarget Name: {name}")
            for match_name, score in high_matches:
                print(f" -> Found: '{match_name}' (Score: {score})")
                processed_names.add(match_name) # Mark as processed
                
        processed_names.add(name)

Scanning for similar names...

Target Name: PA Patel
 -> Found: 'AR Patel' (Score: 88)

Target Name: IK Pathan
 -> Found: 'YK Pathan' (Score: 89)

Target Name: S Dhawan
 -> Found: 'R Dhawan' (Score: 88)

KeyboardInterrupt:

In [73]:
# The meticulously vetted correction dictionary
fuzzy_corrections = {
    'Arshad Khan (2)': 'Arshad Khan',
    'NA Saini': 'N Saini',
    'R Bishnoi': 'Ravi Bishnoi',
    'M.S. Dhoni': 'MS Dhoni',
    'M S Dhoni': 'MS Dhoni'
}

# Apply the corrections across all player columns
player_cols = ['batter', 'bowler', 'non_striker', 'player_of_match', 'wicket_player_out']

for col in player_cols:
    df[col] = df[col].replace(fuzzy_corrections)

print("Player names successfully vetted and sanitized with 100% accuracy!")

Player names successfully vetted and sanitized with 100% accuracy!

In [74]:
# Step 1: Ensure the directory exists (just in case you haven't created the folder yet)
output_dir = Path('../data/processed')

# Step 2: Define the exact file path
output_file = output_dir / 'ipl_cleaned.csv'

# Step 3: Export the DataFrame
# VERY IMPORTANT: index=False prevents pandas from writing the row numbers as a new column
df.to_csv(output_file, index=False)

print(f"Success! Clean data saved to: {output_file}")

Success! Clean data saved to: ../data/processed/ipl_cleaned.csv